### ISSUE TITLE
remove cDock menu icon?

### ISSUE THREAD

**Issue by isanynameavailable** [w0lfschild/cDock#36]
cDock 9.5, OS 10.10.5
after update to 9.5 I have a cDock menu bar icon which I don't need or want, but I can't get rid of it -- how do I do this?
Also, why can't cDock run from the Utilities folder? According to my definition, cDock is more of a utility than an application and I would like to be able to run it from there, if possible.
Apart from these gripes I love cDock and would be very unhappy if i couldn't have a transparent dock -- thanks for taking the time to develop the program.

**Comment by w0lfschild** [comment]
In extra settings there's an option to not start the menu bar application.

To close the menu bar application simply click it and choose the quit option.

It doesn't run from Utilities because Utilities does not have write permissions for anyone but root. Generally nothing should be added to the Utilities folder.

![screen shot 2015-08-26 at 1 49 14 pm](https://cloud.githubusercontent.com/assets/1920148/9505928/e7ed5224-4bf9-11e5-8946-f9246794d13f.png)

Having the app only reside in /Applications is easiest for me to code and much less likely to have issues on different system configurations.

**Comment by isanynameavailable** [comment]
Wolfgang,
	Thank you very much for your rapid and helpful reply. I will leave cDock in Apps and make the appropriate adjustment to the settings so that the menu bar app doesn’t start.

	Thanks again for writing cDock.


	Simon
