### ISSUE TITLE
cDock 2 not really working with macOS Sierra 10.12.3

### ISSUE THREAD

**Issue by bbblueboy** [w0lfschild/cDock#79]
I don't know what I am doing wrong, I am trying to change the color of my dock to another color and it's not working. I think all the other features are just not the color background, I must be an idiot or something. I even booted up in recovery mode and typed "csrutil disable" into the terminal console. Also, question, does that console command make me vulnerable?

**Comment by w0lfschild** [comment]
It's had to tell why it's not working for you without more information. Make sure you're not using the transparent theme because that will not draw a custom background.

Once cDock has installed SIMBL you can turn SIP back on. Technically you are more vulnerable with SIP off than with it on, so it's a good idea to re-enable it after you've made any changes that require turning it off.
